### PR TITLE
Better end of lief cycle

### PR DESCRIPTION
**Pull request by stephanenicolas**
You might want to be sure that the callback is not called after onPause in the activity.

### CODE REVIEW

**Comment by florina-muntenescu** [comment]
@stephanenicolas thanks!

**Comment by stephanenicolas** [comment]
Hi Florina, I didn't want to open an issue for this. But, what do you think
of adding a small extra work to the view model to help understand the
difference with the model, something like: displaying a spinner progress if
the request is pending ?

2016-11-20 16:43 GMT+01:00 Florina Muntenescu notifications@github.com:

**Comment by florina-muntenescu** [comment]
You mean having something slightly more complex, like in [this project](https://github.com/florina-muntenescu/DroidconMVVM) ?

**Comment by stephanenicolas** [comment]
Yes ;)

Le lun. 21 nov. 2016 09:25, Florina Muntenescu notifications@github.com a
écrit :

**Pull request merged**
